### ISSUE TITLE
New Site: Post new site rollout tasks

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/ponylang-website#24]
A slowly growing list of things we will need to do (only add to this list once the related content is in the new site but before it is deployed)
- [x] Update pony+dev wiki content to point to the website
- [ ] Update all COC links to point to COC on website
- [ ] Update all COCs  from various groups.io locations to point at the website
- [x] Make sure Planet Pony on website is up-to-date with groups.io wiki
- [x] Update Planet Pony on groups.io wiki to point to website
- [x] Update State of the Stable 2016 on groups.io wiki to point to entry in website blog

Known COC links:
- groups.io subgroup/group descriptions
- IRC message of the day
- welcome emails from mailing lists
- github repos

**Comment by SeanTAllen** [comment]
@aturley should we have a copy of COC in each repo or just a standard file that points to the COC on the website? whichever we choose might impact on post site rollout tasks. I'm inclined to point people at the website from a CODE_OF_CONDUCT.md in the various repos.

**Comment by SeanTAllen** [comment]
Q: Where I currently say "delete", should we leave the wiki pages in place and have a link pointing to new content on website?

**Comment by aturley** [comment]
I'm in favor of having a copy of the COC in each repo.

I think we should leave the wiki pages with links to new content. That way, if anyone has linked to them they won't end up with useless links.

**Comment by SeanTAllen** [comment]
I think having a copy in each repo is a recipe for things falling out of date. We've seen that already with install instructions being in more than one place and coming out of sync. I think a link in each repo to the COC should be sufficient.

What's your concern with not having an actual copy of the COC in each repo @aturley?

**Comment by aturley** [comment]
My preference was based on reducing the number of clicks that it took to get to information, but after spending some time researching my position I've decided that I'm wrong, or at least not right enough to advocate for a particular position.

So making everything link to a central COC is fine by me.
