### ISSUE TITLE
Last Week in Pony - December 2, 2018

### ISSUE THREAD

**Issue by jdhorwitz** [ponylang/ponylang-website#360]

**Comment by kulibali** [comment]
I'm going to try to keep up with the Advent of Code in Pony: https://github.com/kulibali/advent_of_code_2018

**Comment by aturley** [comment]
I will also be doing Advent of Code in Pony:

https://github.com/aturley/advent-of-code-2018

I will also be streaming work on AoC puzzles from 3PM-4PM (Eastern Standard Time) Monday, Wednesday, and Friday. You can watch the stream on Twitch:

https://www.twitch.tv/aturls

**Comment by SeanTAllen** [comment]
And Richard Kallos' AOC Repo:

https://github.com/rkallos/aoc2018
