### ISSUE TITLE
Add FAQ for "quiescence"

### ISSUE THREAD

**Issue by EpicEric** [ponylang/ponylang-website#502]
i.e. mainly how the GC decides to collect actors or not. Here's [some discussion from Zulip](https://ponylang.zulipchat.com/#narrow/stream/189985-beginner-help/topic/Pony.20vs.20Akka/near/176588560):

>Actors are not gc'd if they are running behaviors:
>
>they must:
>
>- have no aliases to them (cant be sent new messages by other actors)
>- not be registered for events from the runtime (via epoll, kqueue etc)
>- have an empty message queue

**Comment by SeanTAllen** [comment]
We are closing this in favor of adding to the tutorial. We discussed this at the October 22nd, 2019 sync meeting. More context is available in that conversation and in the linked issue:

https://github.com/ponylang/pony-tutorial/issues/408
