### ISSUE TITLE
Add GitHub as a sponsor

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/ponylang-website#566]
We use a lot of free GH services.

**Comment by EpicEric** [comment]
Does this include only repo hosting and CI/CD through GitHub Actions?

Is LFS still being used, and if so, is it now free for the Ponylang org?

**Comment by SeanTAllen** [comment]
repo hosting and CI/CD.

LFS is no longer used since we moved to using the "vendored" llvm.
