### ISSUE TITLE
SSL error on tutorial.ponylang.org

### ISSUE THREAD

**Issue by jasoncarr0** [ponylang/ponylang-website#617]
The SSL certificate used on said page seems to be valid only for gitbooks.io, not ponylang.org

![image](https://user-images.githubusercontent.com/6874204/92296954-0cf1f780-eeef-11ea-9d1d-ec93e900c332.png)

**Comment by EpicEric** [comment]
ponylang.org is a deprecated domain. The tutorial is over at https://tutorial.ponylang.io.

Also, please open any tutorial-related issues in [ponylang/pony-tutorial](https://github.com/ponylang/pony-tutorial).

**Comment by jasoncarr0** [comment]
Thanks for the info, ponlyang.org still appears when searching, so perhaps steps should be taken to deindex it.
