### ISSUE TITLE
Broken and outdated Playground examples

### ISSUE THREAD

**Issue by EpicEric** [ponylang/ponylang-website#665]
With the compiler and playground updates over the years, some playground examples have broken. I thought it'd make sense to check if any links in the website have been broken, since they are the ones we'd probably want to last.

These are the ones I've found (fortunately just a few):

- [blog/last-week-in-pony-04082018.md](https://github.com/ponylang/ponylang-website/blob/0496615feb88002c0ccd9b571c99da1c98d13db2/content/blog/last-week-in-pony-04082018.md) -- [Playground link](https://playground.ponylang.io/?gist=4e93446ff4dc4283e98b0a08db1a78ae)
- [blog/last-week-in-pony-03252018.md](https://github.com/ponylang/ponylang-website/blob/0496615feb88002c0ccd9b571c99da1c98d13db2/content/blog/last-week-in-pony-03252018.md) -- [Playground link](https://is.gd/VPkxXu) (the code is encoded in the non-shortened URL)

---

On a separate but related topic, I've noticed that some gists were uploaded anonymously, instead of on the [ponylang-gist account](https://gist.github.com/ponylang-gist). This behavior was changed when GitHub stopped allowing anonymous gists to be uploaded. Since we don't know if these gists will still live in the future, perhaps these should be re-uploaded?

Here is the list:

- [blog/last-week-in-pony-03042018.md](https://github.com/ponylang/ponylang-website/blob/0496615feb88002c0ccd9b571c99da1c98d13db2/content/blog/last-week-in-pony-03042018.md) -- [Gist link](https://gist.github.com/anonymous/0e31414bb350a315509df5c08850618f)
- [blog/last-week-in-pony-03112018.md](https://github.com/ponylang/ponylang-website/blob/0496615feb88002c0ccd9b571c99da1c98d13db2/content/blog/last-week-in-pony-03112018.md) - [Gist link](https://gist.github.com/anonymous/dc16ebcb1b75682bd385b7b9c078fb46)
- [blog/last-week-in-pony-03182018.md](https://github.com/ponylang/ponylang-website/blob/0496615feb88002c0ccd9b571c99da1c98d13db2/content/blog/last-week-in-pony-03182018.md) - [Gist link](https://gist.github.com/anonymous/c8d70a175b7fde58d42f021e88595a89)
- [blog/last-week-in-pony-073017.md](https://github.com/ponylang/ponylang-website/blob/0496615feb88002c0ccd9b571c99da1c98d13db2/content/blog/last-week-in-pony-073017.md) - [Gist link](https://gist.github.com/anonymous/8835236a430b10147eb640825ba73b5f)
- [faq/index.md](https://github.com/ponylang/ponylang-website/blob/0496615feb88002c0ccd9b571c99da1c98d13db2/content/faq/index.md) - [Gist link](https://gist.github.com/anonymous/26fce9986dd82a58f8bcd5197e22121f)

**Comment by SeanTAllen** [comment]
@jemc I'm not inclined to go back and update code in Last Week in Pony's that no longer work. They are code from a moment in time. That I think is fine if it doesn't work with the latest and greatest version. Much like code in release notes might no longer work.

Thoughts? If you agree, I say we close this, while opening a new issue for the gists.

**Comment by jemc** [comment]
Agreed :+1:
