### ISSUE TITLE
Last Week in Pony - Sept 11th, 2022

### ISSUE THREAD

**Issue by rhagenson** [ponylang/ponylang-website#789]
```pony
use "pony_news"`
```

I opened this so I could put the issues highlight into the (more) correct week. I will be traveling over the next week so I previously discussed with Red me listing 4 issues (as opposed to the usual 2) to cover the next two weeks of LWIP entries.

This week's issues highlight:

- https://github.com/ponylang/ponyc/issues/3244
- https://github.com/ponylang/pony-tutorial/issues/458

Next week's issues highlight:
- https://github.com/ponylang/ponyc/issues/2083
- https://github.com/ponylang/pony-tutorial/issues/446

**Comment by SeanTAllen** [comment]
Version 0.4.2 of ponylang/http_server has been released.
See the [release notes](https://github.com/ponylang/http_server/releases/tag/0.4.2) for more details.

**Comment by SeanTAllen** [comment]
Version 0.51.2 of ponylang/ponyc has been released.
See the [release notes](https://github.com/ponylang/ponyc/releases/tag/0.51.2) for more details.

**Comment by SeanTAllen** [comment]
Version 0.2.2 of seantallen-org/lori has been released.
See the [release notes](https://github.com/seantallen-org/lori/releases/tag/0.2.2) for more details.
