### ISSUE TITLE
Last Week in Pony - Oct 2nd 2022

### ISSUE THREAD

**Issue by redvers** [ponylang/ponylang-website#792]
```pony
use "pony_news"
```

**Comment by SeanTAllen** [comment]
Version 0.3.0 of seantallen-org/lori has been released.
See the [release notes](https://github.com/seantallen-org/lori/releases/tag/0.3.0) for more details.

**Comment by SeanTAllen** [comment]
Version 0.3.0 of seantallen-org/lori has been released.
See the [release notes](https://github.com/seantallen-org/lori/releases/tag/0.3.0) for more details.

**Comment by SeanTAllen** [comment]
A while back, Red Davies started working on a pure Pony Postgres driver to scratch a work itch. After some conversation with Sean T. Allen, it was decided that it would be an excellent official Pony project.

Today, after having played around with some ideas in a repo owned by Red, we created the official repo where we will be doing development going forward. You can follow along at [https://github.com/ponylang/postgres].

**Comment by ponylang-main** [comment]
Version 0.51.3 of ponylang/ponyc has been released.
See the [release notes](https://github.com/ponylang/ponyc/releases/tag/0.51.3) for more details.

**Comment by SeanTAllen** [comment]
There's currently an issue with the mkdocs-ponylang theme. The theme doesn't work with Mkdocs 1.4.0 which was recently released. If you are using the mkdocs-ponylang theme you need to use Mkdocs 1.3.1.

**Comment by SeanTAllen** [comment]
Version 0.4.0 of seantallen-org/lori has been released.
See the [release notes](https://github.com/seantallen-org/lori/releases/tag/0.4.0) for more details.

**Comment by redvers** [comment]
Closed by #793
