### ISSUE TITLE
Last Week in Pony - Oct 16th 2022

### ISSUE THREAD

**Issue by redvers** [ponylang/ponylang-website#794]
```ponyc
use "pony_news"
```

**Comment by rhagenson** [comment]
Issues highlight:

- https://github.com/ponylang/pony-patterns/issues/46
- https://github.com/ponylang/ponyc/issues/3987

**Comment by SeanTAllen** [comment]
A new LibreSSL builder is available. The new version uses LibreSSL 3.5.3. The 3.5.2 builder has been deprecated and will be removed in 6 months.

**Comment by SeanTAllen** [comment]
A new OpenSSL builder is available. The new version uses OpenSSL 1.1.1q. The 1.1.1n builder has been deprecated and will be removed in 6 months.

**Comment by ponylang-main** [comment]
The 'Introduce empty Ranges' RFC has been updated to 'final comment period'
See the [RFC](https://github.com/ponylang/rfcs/pull/201) for more details.

**Comment by SeanTAllen** [comment]
Audio for the October 25, 2022 Pony Development Sync is available: https://sync-recordings.ponylang.io/r/2022_10_25.m4a

**Comment by ponylang-main** [comment]
The 'Add RFC for the inclusion of all erase codes in the Term package' RFC has been updated to 'new'
See the [RFC](https://github.com/ponylang/rfcs/pull/203) for more details.

**Comment by ponylang-main** [comment]
Version 0.51.4 of ponylang/ponyc has been released.
See the [release notes](https://github.com/ponylang/ponyc/releases/tag/0.51.4) for more details.
