### ISSUE TITLE
Last Week in Pony - October 8, 2023

### ISSUE THREAD

**Issue by rhagenson** [ponylang/ponylang-website#891]

**Comment by ponylang-main** [comment]
Version 0.1.5 of ponylang/peg has been released.
See the [release notes](https://github.com/ponylang/peg/releases/tag/0.1.5) for more details.

**Comment by ponylang-main** [comment]
Version 0.1.3 of ponylang/github_rest_api has been released.
See the [release notes](https://github.com/ponylang/github_rest_api/releases/tag/0.1.3) for more details.

**Comment by ponylang-main** [comment]
Version 0.2.4 of ponylang/templates has been released.
See the [release notes](https://github.com/ponylang/templates/releases/tag/0.2.4) for more details.
