### ISSUE TITLE
Color mode switcher

### ISSUE THREAD

**Issue by shaedrich** [ponylang/ponylang-website#978]
It's nice that you include a language switcher on your website. However, it's not exactly apparent that it is one. I guessed, it was and was proven right, but it could have an icon of sorts resembling light and dark.

**Comment by SeanTAllen** [comment]
This is provided by the theme we use. We won't be changing the icon.

If that isn't what you meant, do let me know. Otherwise, if you think something else would be better, I'd open an issue with https://squidfunk.github.io/mkdocs-material/.

**Comment by shaedrich** [comment]
Well, you _could_ change it, as far as I see it:

> The following properties must be set for each toggle:
> 
> [`icon`](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=#+palette.toggle.icon)
> 
> 💧⚠️ This property must point to a valid icon path referencing any icon bundled with the theme, or the build will not succeed. Some popular combinations:
> * ![grafik](https://github.com/ponylang/ponylang-website/assets/11225821/bcf56e77-51ba-4793-bcf2-cb5ef8ec4255) – `material/brightness-7` + `material/brightness-4`
> * ![grafik](https://github.com/ponylang/ponylang-website/assets/11225821/eb30d6b4-531e-44b8-ab67-10db9e8ebf5b) – `material/toggle-switch` + `material/toggle-switch-off-outline`
> * ![grafik](https://github.com/ponylang/ponylang-website/assets/11225821/fff7e1dc-a352-4e04-a482-d23eb4683511) – `material/weather-night` + `material/weather-sunny`
> * ![grafik](https://github.com/ponylang/ponylang-website/assets/11225821/76af968b-18b3-420a-86c6-876467328850) – `material/eye` + `material/eye-outline`
> * ![grafik](https://github.com/ponylang/ponylang-website/assets/11225821/6c4a6c14-c72e-4df3-bf96-5e900b60982f) – `material/lightbulb` + `material/lightbulb-outline`

So, instead of `material/toggle-switch` + `material/toggle-switch-off-outline`, you could use `material/brightness-7` + `material/brightness-4` or `material/weather-night` + `material/weather-sunny`—would that be an option?

https://github.com/ponylang/ponylang-website/blob/cf4c015537179c81c0502b3ebda34255b00a37d7/mkdocs.yml#L86-L100
