### ISSUE TITLE
Page title

### ISSUE THREAD

**Issue by shaedrich** [ponylang/ponylang-website#980]
Why change "Pony Tutorial" (same on other parts of the site, not exclusive to tutorial) to the chapter/page title? Why not keep both? Maybe even the sticky section name?

This could look something like this:
![grafik](https://github.com/ponylang/ponylang-website/assets/11225821/e0ea0b06-f9ef-48fb-a981-65781f26df61)

**Comment by SeanTAllen** [comment]
Did you mean to open this on the tutorial repo?

**Comment by SeanTAllen** [comment]
Btw, this isnt an actionable issue. For discussions of this sort, please start a conversation in Zulip. We have streams related to the tutorial, website etc.

**Comment by shaedrich** [comment]
> Did you mean to open this on the tutorial repo?

No. As I said. This functionality works the same on both the tutorial and the website.
